apiVersion: v1
kind: Pod
metadata:
  name: flask-mysql-pod
spec:
  containers:
  - name: todo-backend
    image: gcr.io/<YOUR_PROJECT_ID>/todo-backend
    ports:
    - containerPort: 5000
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-init-volume
      mountPath: /docker-entrypoint-initdb.d 
  volumes:
  - name: mysql-init-volume
    configMap:
      name: mysql-init-db-config 
