apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
  labels:
    app: todo-app
spec:
  containers:
  - name: todo-backend
    image: gcr.io/<YOUR_PROJECT_ID>/todo-backend
    ports:
    - containerPort: 5000
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-storage
      mountPath: /var/lib/mysql-data
    - name: mysql-init-volume
      mountPath: /docker-entrypoint-initdb.d
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: nginx-html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
  - name: mysql-init-volume
    configMap:
      name: mysql-init-db-config
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: nginx-html-volume
    configMap:
      name: nginx-html-config  # Assume you've created this ConfigMap for your static files
